### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by robweber** [robweber/cronxbmc#13]
From forum: https://forum.kodi.tv/showthread.php?tid=124888&pid=2653730#pid2653730 

Great plugin.
Yet absolutely no foolproof on cron expression input. I've crushed the plugin and made in unstartable when set cron to 8 digits, (not 5-6). Please, add try catch.

**Comment by seanboy201** [comment]
Hi rob I'm not sure how to talk to u but how can I fix the backup error I sell these boxes for a living and have. A left setup saved on my. Jump drive. But dont know to implement it without your backup add on .. Please help. .. Thanks in advance 
Sean graham
Seangram9002@gmail.com

**Comment by robweber** [comment]
I added comment to the issue for the backup addon.

**Comment by seanboy201** [comment]
Hey rob.. Thanks for the link.. Sadly I'm still experiencing another issue
with the add on.. When configuring the to look for the remote path on my
Jump drive same as I've always done . The restore option. The file does not
show up for me to use.  Even though I know it's there's and so does kodi
itself.. Please help me if u can  thanks In  advance...
