### ISSUE TITLE
Job delete

### ISSUE THREAD

**Issue by BlackGlassSkin** [robweber/cronxbmc#19]
Thanks for this addon

I am not able to delete the added task
I can change action, time, name, but not delete completely

<p align="left">
<img src="https://i.ibb.co/p1XFcyJ/2021-01-06-20h19-52.png">

**Comment by robweber** [comment]
Guessing this was in Kodi v19 as that was the only version I could reproduce this with. Kodi 18 worked just fine. Thanks for pointing this out.
