### ISSUE TITLE
add to official kodi repo?

### ISSUE THREAD

**Issue by TermeHansen** [robweber/cronxbmc#24]
Why is this addon not in the official kodi repo?

https://github.com/xbmc/repo-plugins/tree/matrix

**Comment by robweber** [comment]
Good question. I don't recall specifics but I believe there was a reason originally. The very first versions of this didn't even have a GUI and were pretty hard to configure. I think over time it's just gotten a lot more user friendly but I never revisited the idea of submitting it. It wouldn't take much to at least try and get it reviewed.

**Comment by TermeHansen** [comment]
No its fairly easy. Will you do it, or should I do it? I have a PR btw comming up with a fix for relative import in py3 as I would like to use this imy addon 🤓

**Comment by robweber** [comment]
I can prep stuff to get it ready to submit. I like to use Kodi's "auto submitter" tool so I'll cut/paste the workflow from one of my other addons. I'll watch for that PR and get that all worked out first before pushing to the Kodi repo. Thanks for the thoughts on this.

**Comment by TermeHansen** [comment]
https://github.com/robweber/cronxbmc/pull/25

**Comment by robweber** [comment]
I did some cleanup to get this ready for the main Kodi repo. Can you test the matrix branch? No big changes but I did mess with the settings file to make sure it adheres to the new format. Works on my side but two tests is better than one.

**Comment by TermeHansen** [comment]
Sure, I'll post when I have tested later today....

**Comment by TermeHansen** [comment]
Just tested latest from matrix branch, seems to work fine for my use also...

**Comment by robweber** [comment]
Just as an update - I didn't forget about this. I'm having issues the the Kodi addon submitter addon. After fighting with it for a while I decided to just do the PR by hand. I was all ready to submit this to the repo and right before I hit "submit" on the pull request I noticed the addon image still said "XBMC" in it. I'll have to fix it, re-tag, and prepare the PR again. Just wanted to let you know I didn't forget about this, just had some hassles.

**Comment by TermeHansen** [comment]
Any news? I have branch waiting for it 🤓

**Comment by robweber** [comment]
I just updated the logo to remove the XBMC reference. I'll re-do the tag and submit.

**Comment by robweber** [comment]
Pull request: https://github.com/xbmc/repo-scripts/pull/2272

**Comment by robweber** [comment]
Looks like this is good. Thanks for the additions and the comment on the PR pushing this through. I always hesitate to bug the Kodi devs too much, I know reviewing the addons takes time and probably not a fun task.

**Comment by TermeHansen** [comment]
Yes me 2, but also it's hard to know if he waits for me/you to say it is ready for review again...

Feel free to ping me if you need help with PR or tests of kodi addons....
