### ISSUE TITLE
function is removed when cancelling from keyboard box

### ISSUE THREAD

**Issue by Shredder5262** [robweber/cronxbmc#31]
I have just noticed an 'odd' behavior when looking into existing cron jobs Built-in functions.
If for example, I have a job already set up and i navigate into the built-in function where a command for a job exists, the keyboard dialog box opens to display the command. If I select cancel.,..implying that i don't want to alter the job in  any way, the command/function is removed altogether.
IMO this shouldn't work like this, It should leave the existing command in place. I don't know why it deletes it.

**Comment by robweber** [comment]
I read through the functions in the code related to this and couldn't see any reason this should happen on it's own. I'll test it out and see what's going on there.

**Comment by robweber** [comment]
Looks like in the documentation it states that __Cancel__ returns an empty string. I[ added a check for this](https://github.com/robweber/cronxbmc/commit/ae2edd16b654da5716a3847e1c0562d8338f29e9).
