### ISSUE TITLE
Format of Commands

### ISSUE THREAD

**Issue by pieman64** [robweber/cronxbmc#5]
Hi Rob,

Can you please give a few examples for the format of the commands we need to enter in the gui e.g for a script named abc I have tried simply script.abc but the script didn't run at the scheduled time.
Thanks

**Comment by robweber** [comment]
Hi, 

The command has to be a Kodi built in command, ie something from this page: http://kodi.wiki/view/List_of_built-in_functions. 

If you are trying to run a custom python script you can use the RunScript() command. That would look something like "RunScript(/path/to/script.py,arg1,arg2)" or if you are trying to launch an addon you can use "RunAddon(addon.id)". Does that help?
