### ISSUE TITLE
Cron

### ISSUE THREAD

**Issue by kashkash18** [robweber/cronxbmc#6]
Hello, is it possible to add to the repository cronxbmc Ramicspa ??

**Comment by robweber** [comment]
You want to add this addon to that repository? If you want to feel free, the code is available to git pull.

**Comment by kashkash18** [comment]
I would like to add it to the repo for this reason that there is an addition to television and Cron assists in the daily updating services. The idea is to give to install it from one repo, as on a TV with Android TV for installing plugins outside repo is problematic.

**Comment by robweber** [comment]
No reason that shouldn't work. Depending on how your repo is setup you can git pull it and package it or perhaps add it a submodule if you keep the whole thing in git.
