### ISSUE TITLE
Installation error under Krypton

### ISSUE THREAD

**Issue by johnwillson** [robweber/cronxbmc#9]
Tried to install the .zip into a pretty fresh Krypton install and got the following errors.

15:57:11.054 T:2367132656  NOTICE: service.cronxbmc-0.0.5 : Cron for Kodi service starting....
15:57:11.549 T:2350355440  NOTICE: Previous line repeats 1 times.
15:57:11.549 T:2350355440   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: (17, 'File exists', '/home/osmc/.kodi/userdata/addon_data/service.cronxbmc/')
                                            Traceback (most recent call last): 
File "/home/osmc/.kodi/addons/service.cronxbmc/service.py", line 6, in <module>
                                                CronService().runProgram()
File "/home/osmc/.kodi/addons/service.cronxbmc/resources/lib/cron.py", line 156, in __init__
                                                self.manager = CronManager()
File "/home/osmc/.kodi/addons/service.cronxbmc/resources/lib/cron.py", line 23, in __init__
                                                self.jobs = self._readCronFile()
File "/home/osmc/.kodi/addons/service.cronxbmc/resources/lib/cron.py", line 94, in _readCronFile
                                                os.makedirs(xbmc.translatePath(utils.data_dir()))
File "/usr/lib/python2.7/os.py", line 157, in makedirs
                                                mkdir(name, mode)
OSError: (17, 'File exists', '/home/osmc/.kodi/userdata/addon_data/service.cronxbmc/')
                                            -->End of Python script error report<--

**Comment by johnwillson** [comment]
Okay, just tested it and it seems to work just peachy under Krypton, despite the installation error.  Really like being able to see the "next execution for this active job in 30 mins".

Will let you manage or close this issue as appropriate.

**Comment by robweber** [comment]
It looks like it's trying to make a directory that actually exists already. Makes sense it would continue to work as it should still read in the file and keep going. I should probably update this to actually use the built in Kodi file management modules instead of the python os class. I'll keep this open so I can update accordingly. 

For reference to the bug: https://github.com/robweber/cronxbmc/blob/master/resources/lib/cron.py#L94

**Comment by johnwillson** [comment]
Ya, that sounds right.  I was installing it on top of an osmc build, but after a complete "rm -rf" of .kodi, so it's probably from attempts to recreate the directory, rather than encountering a pre-existing directory.

As you say, it just moves on and works correctly, so no urgent worries for the update... it's great just to have the kodi cron gui working again!
